name: darwin
on: [push]
jobs:
  build:
    name: build
    runs-on: [macos-latest]
    strategy:
      matrix:
        go: ["stable", "oldstable"]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Test
        run: go test ./...
