name: windows
on: [push]
jobs:

  build:
    name: build
    runs-on: [ windows-latest ]
    strategy:
      matrix:
        go: [ '1.22', '1.21', '1.20', '1.18', '1.17', '1.16' ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test ./...
